// GENERATED by AitherOS/dev/tools/gen_panel_tiers_ts.py — DO NOT EDIT.
//
// Panel id -> the minimum licence tier that grants it, composed from
//   awkit-backend/entitlement_gating.py  PANEL_FEATURE_MAP
//   services/orchestration/AitherACTA.py      PLANS[*].features
//
// Hand-editing this drifts it from the plans it describes. Regenerate.

export const PANEL_MIN_TIER: Readonly<Record<string, string>> = {
  "aithergraph": "team",
  "analytics": "team",
  "audit": "team",
  "canvas": "developer",
  "commerce": "business",
  "comms": "starter",
  "company-room": "team",
  "content-studio": "team",
  "executive-briefing": "team",
  "generate": "team",
  "iris": "team",
  "knowledge-rag": "team",
  "marketing": "team",
  "marketing-calendar": "team",
  "marketing-dashboard": "team",
  "marketplace": "starter",
  "muse": "business",
  "post-composer": "team",
  "relationship-dashboard": "team",
  "relay": "starter",
  "saga": "business",
  "skill-library": "pro",
  "social": "team",
  "studio": "team",
  "training": "team",
  "voice": "developer",
  "workspace-admin": "team",
  "workspace-intelligence": "team",
  "writer": "team",
  "ws-room": "team",
}
