'use client'

import { useEffect, useState } from 'react'

interface AuditEntry {
  id: string
  doc_type: string
  title: string
  generated_by: string
  status: string
  content_ref: string
  reviewed_by: string | null
  reviewed_at: string | null
  notes: string
  created_at: string | null
}

const STATUS_COLORS: Record<string, string> = {
  draft: 'var(--text-muted)',
  reviewed: 'var(--accent-cyan)',
  approved: 'var(--accent-green)',
  rejected: 'var(--accent-coral)',
}

type StatusFilter = 'all' | 'draft' | 'reviewed' | 'approved' | 'rejected'

export interface AuditPanelProps {
  apiBase?: string
  exportBase?: string
}

export default function AuditPanel({ apiBase = '/api/audit', exportBase = '/api/export' }: AuditPanelProps) {
  const [entries, setEntries] = useState<AuditEntry[]>([])
  const [filter, setFilter] = useState<StatusFilter>('all')

  const fetchAudit = () => {
    fetch(apiBase)
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        const list = Array.isArray(data) ? data
          : Array.isArray(data?.data) ? data.data
          : Array.isArray(data?.entries) ? data.entries
          : []
        setEntries(list)
      })
      .catch(() => setEntries([]))
  }

  useEffect(() => { fetchAudit() }, [apiBase])

  const review = async (id: string, status: string) => {
    await fetch(`${apiBase}/${id}/review`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status }),
    })
    fetchAudit()
  }

  const download = async (entry: AuditEntry) => {
    if (!entry.content_ref) return
    const resp = await fetch(`${exportBase}/download?ref=${encodeURIComponent(entry.content_ref)}`)
    if (!resp.ok) return
    const blob = await resp.blob()
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${entry.title || entry.doc_type}_${entry.id.slice(0, 8)}.docx`
    a.click()
    URL.revokeObjectURL(url)
  }

  const filtered = filter === 'all' ? entries : entries.filter(e => e.status === filter)

  return (
    <div style={{ padding: '1.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h2 style={{ fontSize: '1.1rem' }}>Audit Trail</h2>
        <select
          value={filter}
          onChange={e => setFilter(e.target.value as StatusFilter)}
          style={{
            padding: '0.4rem 0.75rem',
            background: 'var(--bg-surface)',
            color: 'var(--text-primary)',
            border: '1px solid var(--glass-border)',
            borderRadius: 6,
            fontSize: '0.8rem',
          }}
        >
          <option value="all">All Status</option>
          <option value="draft">Draft</option>
          <option value="reviewed">Reviewed</option>
          <option value="approved">Approved</option>
          <option value="rejected">Rejected</option>
        </select>
      </div>

      <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
        All AI-generated documents require human review before sending to clients.
      </p>

      {filtered.length === 0 && (
        <p style={{ color: 'var(--text-muted)', textAlign: 'center', marginTop: '2rem' }}>
          No generated documents{filter !== 'all' ? ` with status "${filter}"` : ''}.
        </p>
      )}

      {filtered.map(e => (
        <div key={e.id} style={{
          background: 'var(--bg-surface)',
          border: '1px solid var(--glass-border)',
          borderRadius: 'var(--radius)',
          padding: '1rem',
          marginBottom: '0.75rem',
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <strong style={{ fontSize: '0.9rem' }}>{e.title || 'Untitled'}</strong>
              <span style={{
                marginLeft: '0.5rem',
                background: 'var(--bg-elevated)',
                padding: '0.1rem 0.4rem',
                borderRadius: 3,
                fontSize: '0.7rem',
              }}>{e.doc_type}</span>
            </div>
            <span style={{
              color: STATUS_COLORS[e.status] || 'var(--text-muted)',
              fontSize: '0.8rem',
              fontWeight: 600,
              textTransform: 'uppercase',
            }}>
              {e.status}
            </span>
          </div>

          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.4rem' }}>
            Generated by {e.generated_by} · {e.created_at ? new Date(e.created_at).toLocaleString() : ''}
            {e.reviewed_by && ` · Reviewed by ${e.reviewed_by}`}
          </div>

          <div style={{ marginTop: '0.75rem', display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            {e.content_ref && (
              <button
                onClick={() => download(e)}
                style={{
                  padding: '0.35rem 0.75rem',
                  background: 'var(--bg-elevated)',
                  color: 'var(--accent-cyan)',
                  borderRadius: 6,
                  fontSize: '0.8rem',
                  border: '1px solid var(--glass-border)',
                }}
              >
                Download
              </button>
            )}

            {e.status === 'draft' && (
              <>
                <button
                  onClick={() => review(e.id, 'approved')}
                  style={{
                    padding: '0.35rem 0.75rem',
                    background: 'var(--accent-green)',
                    color: 'var(--bg-deep)',
                    borderRadius: 6,
                    fontSize: '0.8rem',
                    fontWeight: 600,
                  }}
                >
                  Approve
                </button>
                <button
                  onClick={() => review(e.id, 'reviewed')}
                  style={{
                    padding: '0.35rem 0.75rem',
                    background: 'var(--bg-elevated)',
                    color: 'var(--text-primary)',
                    borderRadius: 6,
                    fontSize: '0.8rem',
                    border: '1px solid var(--glass-border)',
                  }}
                >
                  Mark Reviewed
                </button>
                <button
                  onClick={() => review(e.id, 'rejected')}
                  style={{
                    padding: '0.35rem 0.75rem',
                    background: 'var(--accent-coral)',
                    color: 'var(--bg-deep)',
                    borderRadius: 6,
                    fontSize: '0.8rem',
                    fontWeight: 600,
                  }}
                >
                  Reject
                </button>
              </>
            )}
          </div>
        </div>
      ))}
    </div>
  )
}
