// The Academy record tools (.PRODUCTS/.ACADEMY layer 7) -- test_awkit_academy_panels_wired pins it.
// AcademyLessonStudioPanel is retired into Aither Classroom (registry.ts RETIRED_PANELS): not exported
// here (PRP: an exported panel needs a registry entry); 'awkit/panels/AcademyLessonStudioPanel' still resolves.
export { default as AcademyAnalyticsPanel } from './AcademyAnalyticsPanel'
export type { AcademyAnalyticsPanelProps } from './AcademyAnalyticsPanel'
export { default as AcademyStudentProfilesPanel } from './AcademyStudentProfilesPanel'
export type { AcademyStudentProfilesPanelProps } from './AcademyStudentProfilesPanel'
export { default as AcademyLessonsPanel } from './AcademyLessonsPanel'
export type { AcademyLessonsPanelProps } from './AcademyLessonsPanel'
// Aither Learn (family tutor): the child's quest and the guardian's console.
export { default as KidQuestPanel } from './KidQuestPanel'
export type { KidQuestPanelProps } from './KidQuestPanel'
export { default as FamilyTutorConsolePanel } from './FamilyTutorConsolePanel'
export type { FamilyTutorConsolePanelProps } from './FamilyTutorConsolePanel'
export { default as FamilySpaceCard } from './FamilySpaceCard'
export type { FamilySpaceCardProps } from './FamilySpaceCard'
export { default as KidInboxCard } from './KidInboxCard'
export type { KidInboxCardProps } from './KidInboxCard'
export { default as FamilyMessagesSection } from './FamilyMessagesSection'
export type { FamilyMessagesSectionProps } from './FamilyMessagesSection'
export { default as TutorFocusCard } from './TutorFocusCard'
export type { TutorFocusCardProps } from './TutorFocusCard'
export { default as TutorProgressCard } from './TutorProgressCard'
export type { TutorProgressCardProps } from './TutorProgressCard'
export { default as TutorLevelCard } from './TutorLevelCard'
export type { TutorLevelCardProps } from './TutorLevelCard'
// Aither Classroom (the schools version of Aither Learn): teacher, parent and kid surfaces.
export { default as ClassroomConsolePanel } from './ClassroomConsolePanel'
export type { ClassroomConsolePanelProps } from './ClassroomConsolePanel'
export { default as ClassroomRosterSheet } from './ClassroomRosterSheet'
export type { ClassroomRosterSheetProps } from './ClassroomRosterSheet'
export { default as ClassroomSpriteStrip } from './ClassroomSpriteStrip'
export type { ClassroomSpriteStripProps } from './ClassroomSpriteStrip'
export { default as ClassroomStudioPanel } from './ClassroomStudioPanel'
export type { ClassroomStudioPanelProps } from './ClassroomStudioPanel'
export { default as ClassroomInsightsPanel } from './ClassroomInsightsPanel'
export type { ClassroomInsightsPanelProps } from './ClassroomInsightsPanel'
export { default as ClassroomRoomPanel } from './ClassroomRoomPanel'
export type { ClassroomRoomPanelProps } from './ClassroomRoomPanel'
export { default as ClassroomParentPanel } from './ClassroomParentPanel'
export type { ClassroomParentPanelProps } from './ClassroomParentPanel'
export { default as ClassroomFamilyLinkPanel, ClassroomFamilySeatsPanel } from './ClassroomFamilyLinkPanel'
export type { ClassroomFamilyLinkPanelProps, ClassroomFamilySeatsPanelProps } from './ClassroomFamilyLinkPanel'
export { default as ClassroomNoticesBell } from './ClassroomNoticesBell'
export type { ClassroomNoticesBellProps, ClassroomNotice, NoticePreference } from './ClassroomNoticesBell'
export { default as ClassroomAiPanel } from './ClassroomAiPanel'
export type { ClassroomAiPanelProps } from './ClassroomAiPanel'
export { default as KidAssignmentsCard } from './KidAssignmentsCard'
export type { KidAssignmentsCardProps } from './KidAssignmentsCard'
export { default as KidAssignmentView } from './KidAssignmentView'
export type { KidAssignmentViewProps } from './KidAssignmentView'
export { CLASSROOM_API, ClassroomHttpError, openClassroomStream } from './classroomApi'
export type { ParentChild as ClassroomParentChild, KidAssignment as ClassroomKidAssignment } from './classroomApi'
// Class Website Publisher / Class Website: Academy record tools, named Classroom* in code only.
export { default as ClassroomPublisherPanel } from './ClassroomPublisherPanel'
export type { ClassroomPublisherPanelProps } from './ClassroomPublisherPanel'
export { default as ClassroomSiteViewerPanel } from './ClassroomSiteViewerPanel'
export type { ClassroomSiteViewerPanelProps } from './ClassroomSiteViewerPanel'
export { default as ConnectivityWizardPanel } from './ConnectivityWizardPanel'
export type { ConnectivityWizardPanelProps } from './ConnectivityWizardPanel'
export { default as ActivityFeedPanel } from './ActivityFeedPanel'
export { default as AgentDispatchPanel } from './AgentDispatchPanel'
export { default as AgentsPanel } from './AgentsPanel'
export { default as AitherWriterPanel } from './AitherWriterPanel'
export type { AitherWriterPanelProps } from './AitherWriterPanel'
export { default as AnalyticsPanel } from './AnalyticsPanel'
export { default as AppliancePanel, APPLIANCE_PANEL_TABS } from './AppliancePanel'
export type { AppliancePanelProps } from './AppliancePanel'
export { default as AutonomyRoadmapPanel } from './AutonomyRoadmapPanel'
export { default as ApprovalQueue } from './ApprovalQueue'
export { default as ApprovalsInboxPanel } from './ApprovalsInboxPanel'
export { default as AuditPanel } from './AuditPanel'
export { default as BatchUploadPanel } from './BatchUploadPanel'
export { default as BlogPanel } from './BlogPanel'
export type { BlogPanelProps } from './BlogPanel'
export { default as BookingPanel } from './BookingPanel'
export { default as CalendarPanel } from './CalendarPanel'
export { default as CertificateAuthorityPanel } from './CertificateAuthorityPanel'
export type { CertificateAuthorityPanelProps } from './CertificateAuthorityPanel'
export { default as CMSPanel } from './CMSPanel'
export type { CMSPanelProps } from './CMSPanel'
export { default as ChatPanel } from './ChatPanel'
export { default as ClientsPanel } from './ClientsPanel'
export { default as CommsPanel } from './CommsPanel'
export { default as RelayEmbedPanel } from './RelayEmbedPanel'
export type { RelayEmbedPanelProps } from './RelayEmbedPanel'
export { default as ContactsPanel } from './ContactsPanel'
export { default as ContentStudioPanel } from './ContentStudioPanel'
// Creator Stack (Saga / Media Forge / Iris). Built, then unexported and unkeyed
// for weeks: no pack could enable them. test_awkit_creator_panels_wired pins it.
export { default as SagaPlayPanel } from './SagaPlayPanel'
export { default as StudioPanel } from './StudioPanel'
export { default as IrisPanel } from './IrisPanel'
// .PROVISION layer 5: the company.yaml editor
export { default as ProvisionPanel } from './ProvisionPanel'
export { default as CreateWorkspaceWizard } from './CreateWorkspaceWizard'
export { default as DashboardPanel } from './DashboardPanel'
export { default as DataPlanePanel } from './DataPlanePanel'
export { default as DatabasePanel } from './DatabasePanel'
export { default as DebugPanel } from './DebugPanel'
export { default as DecisionsPanel } from './DecisionsPanel'
export { default as DirectoryPanel } from './DirectoryPanel'
export { default as DocumentPanel } from './DocumentPanel'
export { default as DocumentLifecyclePanel } from './DocumentLifecyclePanel'
export { default as ESignPanel } from './ESignPanel'
export { default as FileSyncPanel } from './FileSyncPanel'
export { default as FormsPanel } from './FormsPanel'
export { default as ForumPanel } from './ForumPanel'
export { default as GeneratePanel } from './GeneratePanel'
export { default as IntegrationsPanel } from './IntegrationsPanel'
export { default as InvoicingPanel } from './InvoicingPanel'
export { default as StripeCommercePanel } from './StripeCommercePanel'
export { default as AwrtifactPanel } from './AwrtifactPanel'
export { default as StrataPanel } from './StrataPanel'
export type { StrataPanelProps } from './StrataPanel'
export { default as AwprovePanel } from './AwprovePanel'
export { default as MyScopesPanel } from './MyScopesPanel'
export type { MyScopesPanelProps } from './MyScopesPanel'
export { default as KvHandoffPanel } from './KvHandoffPanel'
export { default as EmbedMigratePanel } from './EmbedMigratePanel'
export { default as GymPanel } from './GymPanel'
export { default as TaxDeskPanel } from './TaxDeskPanel'
export { default as ThemisLegalPanel } from './ThemisLegalPanel'
export { default as SecretguardPanel } from './SecretguardPanel'
export { default as SpritePanel } from './SpritePanel'
export type { SpritePanelProps } from './SpritePanel'
export { default as KnowledgeRAGPanel } from './KnowledgeRAGPanel'
export type { KnowledgeRAGPanelProps } from './KnowledgeRAGPanel'
export { default as CapturePanel } from './CapturePanel'
export type { CapturePanelProps } from './CapturePanel'
export { default as LLMConfigPanel } from './LLMConfigPanel'
export { default as MailPanel } from './MailPanel'
export { default as OnboardingWizardPanel } from './OnboardingWizardPanel'
export { default as PacksPanel } from './PacksPanel'
export type { PacksPanelProps } from './PacksPanel'
export { default as MyPacksPanel } from './MyPacksPanel'
export type { MyPacksPanelProps } from './MyPacksPanel'
export { default as CreatorPanel } from './CreatorPanel'
export { default as ExperimentsPanel } from './ExperimentsPanel'
export type { ExperimentsPanelProps } from './ExperimentsPanel'
export { default as TrainingJobsPanel } from './TrainingJobsPanel'
export type { TrainingJobsPanelProps } from './TrainingJobsPanel'
export { default as FineTunePanel } from './FineTunePanel'
export type { FineTunePanelProps } from './FineTunePanel'
export { default as McpEndpointsPanel } from './McpEndpointsPanel'
export type { McpEndpointsPanelProps } from './McpEndpointsPanel'
export { default as NanoBrainPanel } from './NanoBrainPanel'
export type { NanoBrainPanelProps } from './NanoBrainPanel'
export { default as PeoplePanel } from './PeoplePanel'
export { default as PlatformPanel } from './PlatformPanel'
export { default as PollPanel } from './PollPanel'
export type { PollPanelProps } from './PollPanel'
export { default as PollEmbedPanel } from './PollEmbedPanel'
export type { PollEmbedPanelProps } from './PollEmbedPanel'
export { default as PollWidget } from './PollWidget'
export type { PollWidgetProps } from './PollWidget'
export { default as ProfilePanel } from './ProfilePanel'
export { default as PortalFiles } from './PortalFiles'
export { default as PortalShell } from './PortalShell'
export { default as PreferencesPanel } from './PreferencesPanel'
export { default as PlanBLedgerPanel } from './PlanBLedgerPanel'
export { default as QuickActionsPanel } from './QuickActionsPanel'
export { default as ReliabilityDashboard } from './ReliabilityDashboard'
export { default as RequestsPanel } from './RequestsPanel'
export { default as InferenceConfigPanel } from './InferenceConfigPanel'
export { default as SecretsPanel } from './SecretsPanel'
export { default as ShopDeployPanel } from './ShopDeployPanel'
export type { ShopDeployPanelProps } from './ShopDeployPanel'
export { default as ShopConnectionPanel } from './ShopConnectionPanel'
export type { ShopConnectionPanelProps } from './ShopConnectionPanel'
export { default as ProductCatalogPanel } from './ProductCatalogPanel'
export type { ProductCatalogPanelProps } from './ProductCatalogPanel'
export { default as SettingsPanel } from './SettingsPanel'
export { default as AccessPolicyPanel } from './AccessPolicyPanel'
export { default as ManagedAgentsPanel } from './ManagedAgentsPanel'
export { default as ConnectorsPanel } from './ConnectorsPanel'
export { default as DoorPeoplePanel } from './DoorPeoplePanel'
export { default as SSOSettingsPanel } from './SSOSettingsPanel'
export type { SSOSettingsPanelProps, SSOConfig } from './SSOSettingsPanel'
export { default as SocialPanel } from './SocialPanel'
export { default as TaskBoardPanel } from './TaskBoardPanel'
export { default as TasksPanel } from './TasksPanel'
export type { TasksPanelProps } from './TasksPanel'
export { default as WebhooksPanel } from './WebhooksPanel'
export { default as RelayChannelsPanel } from './RelayChannelsPanel'
export { default as UserAnalyticsDashboard } from './UserAnalyticsDashboard'
export { default as WorkspaceAdminPanel } from './WorkspaceAdminPanel'
export { default as AitherGraphPanel } from './AitherGraphPanel'
export type { AitherGraphPanelProps } from './AitherGraphPanel'
export { default as BeadSpacePanel } from './BeadSpacePanel'
export type { BeadSpacePanelProps } from './BeadSpacePanel'
export { default as OnDevicePanel } from './OnDevicePanel'
export type { OnDevicePanelProps } from './OnDevicePanel'
export { default as MyHardwarePanel } from './MyHardwarePanel'
export type { MyHardwarePanelProps } from './MyHardwarePanel'
export { default as EscalationsPanel } from './EscalationsPanel'
export { default as WorkspaceConfigPanel } from './WorkspaceConfigPanel'
export { default as WorkspaceCyclesPanel } from './WorkspaceCyclesPanel'
export { default as ExecutionAuditPanel } from './ExecutionAuditPanel'
export { default as BrandDesignerPanel } from './BrandDesignerPanel'
export { default as FeatureMarketplacePanel } from './FeatureMarketplacePanel'
export { default as DataSourceSetupPanel } from './DataSourceSetupPanel'
export type { DataSourceSetupPanelProps } from './DataSourceSetupPanel'
export { default as ProtonSuitePanel } from './ProtonSuitePanel'
export type { ProtonSuitePanelProps } from './ProtonSuitePanel'
export { default as ProtonDrivePanel } from './ProtonDrivePanel'
export type { ProtonDrivePanelProps } from './ProtonDrivePanel'
export { default as ProtonVPNPanel } from './ProtonVPNPanel'
export type { ProtonVPNPanelProps } from './ProtonVPNPanel'
export { default as ProtonPassPanel } from './ProtonPassPanel'
export type { ProtonPassPanelProps } from './ProtonPassPanel'
export { default as SocialGraphPanel } from './SocialGraphPanel'
export type { SocialGraphPanelProps } from './SocialGraphPanel'
export { default as AgentBuilderWizard } from './AgentBuilderWizard'
export type { AgentBuilderWizardProps } from './AgentBuilderWizard'
export { default as PackCard } from './PackCard'
export type { PackCardProps, PackCardPack } from './PackCard'
export { default as PackCatalog } from './PackCatalog'
export type { PackCatalogProps } from './PackCatalog'
export { default as AgentPreviewChat } from './AgentPreviewChat'
export type { AgentPreviewChatProps } from './AgentPreviewChat'
export { default as ModelBrowser } from './ModelBrowser'
export type { ModelBrowserProps } from './ModelBrowser'
export { default as LLMProviderConfig } from './LLMProviderConfig'
export type { LLMProviderConfigProps, LLMProviderSettings } from './LLMProviderConfig'
export { default as CheckoutSummary } from './CheckoutSummary'
export type { CheckoutSummaryProps, LineItem } from './CheckoutSummary'
export { default as FleetDashboard } from './FleetDashboard'
export type { FleetDashboardProps } from './FleetDashboard'
export { default as GridPanel } from './GridPanel'
export type { GridPanelProps } from './GridPanel'
export { default as ErasePanel } from './ErasePanel'
export type { ErasePanelProps } from './ErasePanel'

export { default as PagesPanel } from './PagesPanel'
export type { PagesPanelProps } from './PagesPanel'
export { default as NotebooksPanel } from './NotebooksPanel'
export type { NotebooksPanelProps } from './NotebooksPanel'
export { default as DynamicPanelRenderer, PANEL_COMPONENTS } from './DynamicPanelRenderer'
export type { DynamicPanelRendererProps } from './DynamicPanelRenderer'

// Panel registry
export { PANEL_REGISTRY, RETIRED_PANELS, getPanelById, getRetiredPanel, getPanelsByCategory, getDefaultPanelIds, CATEGORY_LABELS } from './registry'
export type { PanelMeta, PanelCategory, RetiredPanel } from './registry'

// Re-export prop types for consumer use
export type { ActivityFeedPanelProps } from './ActivityFeedPanel'
export type { AnalyticsPanelProps } from './AnalyticsPanel'
export type { AutonomyRoadmapPanelProps } from './AutonomyRoadmapPanel'
export type { AuditPanelProps } from './AuditPanel'
export type { BatchUploadPanelProps } from './BatchUploadPanel'
export type { BookingPanelProps } from './BookingPanel'
export type { CalendarPanelProps } from './CalendarPanel'
export type { ClientsPanelProps } from './ClientsPanel'
export type { ContactsPanelProps } from './ContactsPanel'
export type { ContentStudioPanelProps } from './ContentStudioPanel'
export type { SagaPlayPanelProps } from './SagaPlayPanel'
export type { StudioPanelProps } from './StudioPanel'
export type { IrisPanelProps } from './IrisPanel'
export type { ProvisionPanelProps, CompanyConfig, CompanyAgent } from './ProvisionPanel'
export type { DashboardPanelProps, StatCard } from './DashboardPanel'
export type { DataPlanePanelProps } from './DataPlanePanel'
export type { DatabasePanelProps } from './DatabasePanel'
export type { DebugPanelProps } from './DebugPanel'
export type { DirectoryPanelProps } from './DirectoryPanel'
export type { FileSyncPanelProps } from './FileSyncPanel'
export type { FormsPanelProps } from './FormsPanel'
export type { ForumPanelProps } from './ForumPanel'
export type { GeneratePanelProps } from './GeneratePanel'
export type { InferenceConfigPanelProps } from './InferenceConfigPanel'
export type { IntegrationsPanelProps, IntegrationDef, IntegrationField } from './IntegrationsPanel'
export type { InvoicingPanelProps } from './InvoicingPanel'
export type { MailPanelProps } from './MailPanel'
export type { OnboardingWizardPanelProps } from './OnboardingWizardPanel'
export type { PeoplePanelProps } from './PeoplePanel'
export type { PortalShellProps, NavItem } from './PortalShell'
export type { ProfilePanelProps } from './ProfilePanel'
export type { PreferencesPanelProps } from './PreferencesPanel'
export type { QuickActionsPanelProps, QuickAction } from './QuickActionsPanel'
export type { PlanBLedgerPanelProps } from './PlanBLedgerPanel'
export type { RequestsPanelProps } from './RequestsPanel'
export type { SecretsPanelProps } from './SecretsPanel'
export type { SocialPanelProps } from './SocialPanel'
export type { TaskBoardPanelProps } from './TaskBoardPanel'
export type { WebhooksPanelProps } from './WebhooksPanel'
