// GENERATED by AitherOS/dev/tools/gen_app_licenses_ts.py — DO NOT EDIT.
//
// License id -> the ACTA features it grants, from config/app_licenses.yaml
// (the app-license registry, app-gating plane). The client answers
// hasLicense(id) = hasFeature(...LICENSE_GRANTS[id]) through
// use-entitlements; the server gate reads the same grants server-side.
//
// Hand-editing this drifts it from the registry it describes. Regenerate.

export const LICENSE_GRANTS: Readonly<Record<string, readonly string[]>> = {
}
