/**
 * AUTO-GENERATED by gen_capability_surfaces.py from AitherOS/config/capability-manifest.yaml -- do not edit. Regenerate with: python AitherOS/dev/tools/gen_capability_surfaces.py
 */
import type { AitherApp } from "./apps-manifest";

export const CAPABILITY_APPS: AitherApp[] = [
  {
    id: 'admin-boot-codes',
    name: 'Boot Codes',
    description: 'Mint codes for the aitherium.com boot gate',
    icon: 'key-round',
    route: '/mission-control?tab=tenants&view=boot-codes',
    category: 'admin',
    status: 'stable',
    requiresAuth: true,
    availability: 'full-stack',
    minRole: 'admin',
    showInNav: true,
    keywords: ['boot', 'codes', 'gate', 'mint', 'aitherium'],
    desktopWidget: {
      widgetId: 'boot-codes',
      defaultSize: { width: 800, height: 640 },
      icon: 'key-round',
    },
  },
];
