// GENERATED — DO NOT EDIT.
// Synced from the canonical Bonsai webml runtime (the AitherVeil source
// tree in the AitherOS monorepo). Edit the canonical copy and re-run the
// sync; a hand edit here is overwritten on the next run.
/* SPDX-License-Identifier: LicenseRef-Aitherium-Proprietary
 * © 2026 Aitherium, LLC. Original work.
 *
 * A SIDE CHANNEL FOR IMAGES, so a picture never travels through the text stream.
 *
 * A tool executor returns a STRING, and that string goes two places: into the reply the
 * visitor reads, and into the MODEL's context as the tool observation. Neither can carry an
 * image. Sending base64 down that path fails twice over:
 *
 *   - `stripMarkersStreaming` strips exactly one vocabulary (`[[do:…]]`), so any other
 *     marker is streamed VERBATIM into the reply bubble — the visitor watches megabytes of
 *     base64 type themselves out, which is the same defect that once had raw tool-call JSON
 *     typing itself into the answer;
 *   - the observation is fed back to the model, so the image also consumes the context
 *     window and teaches it to echo the bytes back.
 *
 * So the executor pushes the image HERE and returns a short sentence. The worker drains this
 * after the tool runs and posts the image on its own message type, which the host renders
 * directly. The model is told an image exists; it never sees the bytes.
 *
 * Module-level on purpose, mirroring `toolContext` in registry.ts: the executor is called
 * deep inside the orchestrator with no channel back to the worker loop, and threading one
 * through every tool signature to serve a single tool would be worse than a sink whose whole
 * contract is "written by one executor, drained once, immediately".
 *
 * DRAINING IS DESTRUCTIVE BY DESIGN. A sink that is read without clearing re-posts the same
 * image on every subsequent tool call in the turn — the visitor sees the picture they asked
 * for, then sees it again after every unrelated tool. `drainImages()` is the only reader.
 */

export interface PendingImage {
  /** A complete `data:` URL, ready to put in an <img src>. Never a bare base64 blob. */
  dataUrl: string;
  /** The prompt that produced it, for alt text — an image with no alt is invisible to a
   *  screen reader, and this one is generated content nobody else can describe. */
  alt: string;
}

let pending: PendingImage[] = [];

/**
 * Cap the queue. One turn asking for twenty images would otherwise hold twenty
 * multi-megabyte data URLs in memory until the turn ends, on a page that is simultaneously
 * running a language model on the GPU.
 */
const MAX_PENDING = 4;

/** Called by a tool executor that produced an image. */
export function pushImage(img: PendingImage): void {
  if (!img?.dataUrl) return;
  if (pending.length >= MAX_PENDING) return;
  pending.push(img);
}

/**
 * Take everything queued and CLEAR it. The only reader.
 *
 * Returns a fresh array so a caller holding the result cannot mutate the sink, and so a
 * later push cannot retroactively appear in an already-delivered batch.
 */
export function drainImages(): PendingImage[] {
  if (!pending.length) return [];
  const out = pending;
  pending = [];
  return out;
}

/** Drop anything queued without delivering it. For turn teardown and aborts — an image
 *  generated by a turn the visitor cancelled must not surface in the next one. */
export function clearImages(): void {
  pending = [];
}

/** Queue depth, for tests and diagnostics. Never used to decide anything. */
export function pendingImageCount(): number {
  return pending.length;
}
